---
title: "Untitled"
author: "Jaime Velez"
date: "8 de abril de 2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("FactoMineR")
library("factoextra")
library("gplots")
library(readxl)




base <- read_excel("BF_CON_ETQ.xlsx")
#View(Autoevaluacion_6_11)
#ncol(ae611)
#base = base[base$B==2,]

#tod=c("IDALUMNO", "FECHA",    "S",        "C",        "SEXO",     "B",     "P1_COD1", "P1_COD2",  "P2",       "P3" ,      "P4",       "P5",       "P6" ,      "P7_COD1", "P7_COD2",  "P7_COD3",  "P8",       "P9" ,      "P10",      "P11",      "P12",     "P13",      "P14_COD1", "P14_COD2", "P14_COD3" ,"P15",      "P16",      "P17"  ,   "P18",      "P19",      "P20_COD1", "P20_COD2", "P20_COD3", "P21"  ,    "P22"  ,   "P23",      "P24",      "P25",      "P26_COD1", "P26_COD2", "P26_COD3", "P26_COD4","P27",      "P28"  ,    "P29"  ,    "P30"  ,    "P31"  ,    "P32_COD1", "P32_COD2","P32_COD3")

var2=c( "C","SEXO" , "B",  "P2",       "P3" ,      "P4",       "P5",       "P6"      ,  "P8",       "P9" ,      "P10",      "P11",      "P12",     "P13" ,"P15",      "P16",      "P17"  ,   "P18",      "P19", "P21"  ,    "P22"  ,   "P23",      "P24",      "P25","P27",      "P28"  ,    "P29"  ,    "P30"  ,    "P31"  )

inputPanel(
  selectInput("f", label = "Variable fila:",
              choices = var2, selected = "S"),
    selectInput("c", label = "Variable columna:",
              choices = var2, selected = "C") 
)

```
```{r}

# 2. Graph
renderPlot({
  var=c(input$f,input$c)
dt <- as.table(cbind(table(base[var]),rowSums(table(base[var]))))
dt <- as.table(rbind(dt,colSums(dt)))
a=length(colnames(dt))-1
b=length(rownames(dt))-1
colnames(dt) <- c( colnames(dt)[1:a],"Total Colunmas")
rownames(dt)<- c( rownames(dt)[1:b],"Total Filas")

  
  balloonplot(t(dt), main ="Cruce de variables", xlab =paste(var[2]), ylab=var[1],
            label = T,label.size=2 ,show.margins = FALSE,cum.margins=TRUE)
})

renderPlot({
  var=c(input$f,input$c)
t1=round(table(base[var])/sum(table(base[var])),4)
dt <- as.table(cbind(t1,rowSums(t1)))

dt <- as.table(rbind(dt,colSums(dt)))

a=length(colnames(dt))-1
b=length(rownames(dt))-1
colnames(dt) <- c( colnames(dt)[1:a],"Total Colunmas")
rownames(dt)<- c( rownames(dt)[1:b],"Total Filas")

  
  balloonplot(t(dt), main ="Cruce de variables", xlab =paste(var[2]), ylab=var[1],
            label = T,label.size=2 ,show.margins = FALSE,cum.margins=TRUE)
})

```



```{r}
library(questionr)
renderText({
var=c(input$f,input$c)
t1 <- table(base[var])
chisq <- chisq.test(t1)
chisq$p.value
cramer.v(t1,correct=T)
})
renderText({
var=c(input$f,input$c)
t1 <- table(base[var])
chisq <- chisq.test(t1)
chisq$p.value

})



```

```{r warning=FALSE}
library("FactoMineR")
library("factoextra")
library("gplots")
library(readxl)
library(questionr)



vv=matrix(c(0,0,0,0),ncol=2)
base <- read_excel("BF_CON_ETQ.xlsx")
#View(Autoevaluacion_6_11)
#ncol(ae611)
base = base[base$B==2,]
clo=c( "C","SEXO" , "B",  "P2",       "P3" ,      "P4",       "P5",       "P6"      ,  "P8",       "P9" ,      "P10",      "P11",      "P12",     "P13" ,"P15",      "P16",      "P17"  ,   "P18",      "P19", "P21"  ,    "P22"  ,   "P23",      "P24",      "P25","P27",      "P28"  ,    "P29"  ,    "P30"  ,    "P31"  )

#[1:round(length(clo)/2)]

for(n1 in clo){
  for(n2 in clo){
if(n1 != n2){
    try({
    var=c(n1,n2)
t1 <-(table(base[var]))




dt <- as.table(cbind(table(base[var]),rowSums(table(base[var]))))
dt <- as.table(rbind(dt,colSums(dt)))
a=length(colnames(dt))-1
b=length(rownames(dt))-1
colnames(dt) <- c( colnames(dt)[1:a],"Total Colunmas")
rownames(dt)<- c( rownames(dt)[1:b],"Total Filas")

# 2. Graph

chisq <- chisq.test(t1)
if (cramer.v(t1)
 > 0.1)
{print(c(n1,n2))}
vv=rbind(vv,t(c(n1,n2)))
    }, T )}

}}
```


